create database dairy_farm_project;

use dairy_farm_project;


CREATE TABLE dairy_info (
    Location VARCHAR(100),
    Total_Land_Area DECIMAL(10,2),
    Number_of_Cows INT,
    Farm_Size VARCHAR(100),
    Date_tr DATE,
    Product_ID INT,
    Product_Name VARCHAR(100),
    Brand VARCHAR(100),
    Quantity DECIMAL(10,2),
    Price_per_Unit DECIMAL(10,2),
    Total_Value DECIMAL(10,2),
    Shelf_Life INT,
    Storage_Condition VARCHAR(100),
    Production_Date DATE,
    Expiration_Date DATE,
    Quantity_Sold DECIMAL(10,2),
    Price_per_Unit_Sold DECIMAL(10,2),
    Approx_Total_Revenue DECIMAL(10,2),
    Customer_Location VARCHAR(100),
    Sales_Channel VARCHAR(100),
    Quantity_in_Stock DECIMAL(10,2),
    Min_Stock_Threshold DECIMAL(10,2),
    Reorder_Quantity DECIMAL(10,2)
);

select*from dairy_info;

-- 1) Total revenue generated by each product
select Product_Name, SUM(approx_total_revenue) as total_revenue_by_each_product
from dairy_info
group by Product_Name
order by total_revenue_by_each_product desc;


-- 2) Brand with the highest total revenue
select Brand,sum(approx_total_revenue) as total_brand_revenue
from dairy_info
group by Brand
order by total_brand_revenue desc;

-- 3) Monthly revenue trend across all product
select month(production_date) as months,count(approx_total_revenue) from dairy_info group by months order by months;

-- 4) Products below the min stock threshold
select product_name,brand,Min_stock_threshold,Quantity_in_stock
from dairy_info
where Quantity_in_stock < Min_stock_threshold;

-- 5) Total recorded qty required per product
select Product_Name, sum(reorder_quantity) as Total_Quantity_Reorded
from dairy_info
group by Product_Name
order by Total_Quantity_Reorded desc;

-- 6) Which sales channel generated the most revenue
select Sales_Channel,SUM(approx_Total_Revenue) AS Total_CHANNEL_Revenue
from dairy_info
group by Sales_Channel
order by Total_CHANNEL_Revenue desc limit 1 ;


-- 7) Top 5 customers location by purchases
select Customer_Location, sum(approx_total_Revenue) as total_customers_revenue
from dairy_info
group by Customer_Location
order by total_customers_Revenue desc limit 5;


-- 8) Avg selling price per product
select Product_Name, avg(Price_per_Unit_sold) as avg_price
from dairy_info
group by Product_Name
order by avg_price desc ;


-- 9) Compare selling price with listed price 
select product_name,price_per_unit_sold ,price_per_unit
from dairy_info;


-- 10) Products with less than 10 days shelf life remaining---match
select product_name,brand,shelf_life as shelf_life_below_10days
from dairy_info
where shelf_life<10;


-- 11) Avg shelf life by product category
select Product_Name, avg(Shelf_Life) as avg_shelf_life_days
from dairy_info
group by Product_Name
order by avg_shelf_life_days desc ;


-- 12) Avg no. of cows per farm size category
select Farm_size,avg(number_of_cows) as avg_no_of_cows
from dairy_info
group by Farm_size
order by avg_no_of_cows desc;



-- 13) Location with the largest total land area
select Location, sum(Total_Land_AREA) as total_area
from dairy_info
group by Location
order by total_area desc limit 1;



-- 14) Top 3 location by average production qty
select Location,avg(Quantity)as avg_qty
from dairy_info
group by Location
order by avg_qty desc limit 3;


-- 15) Calculate profit for each product
select product_name,
sum(approx_total_revenue -(quantity_sold * price_per_unit)) as profit
from dairy_info
group by product_name
order by profit desc;

-- 16) Most profitable brand overall
select brand,
sum(approx_total_revenue -(quantity_sold * price_per_unit)) as profit
from dairy_info
group by brand
order by profit desc limit 1;


-- 17) Yearly revenue growth
select year(date_tr) as Years, sum(approx_total_revenue) as Yearly_Revenue
from dairy_info
group by years order by years;

-- 18) Best selling product each yr
select year(date_tr) as years, product_name,
sum(quantity_sold) as qty_sold
from dairy_info
group by year(date_tr),product_name 
order by years, qty_sold desc;

-- 19) Products that need immediate restock
select product_name,brand,min_stock_threshold,quantity_in_stock,reorder_quantity
from dairy_info
where quantity_in_stock<=1
order by product_name;

-- 20 Identify expired products still in stock
select location,product_name,expiration_date,quantity_in_stock
from dairy_info
where expiration_date< current_date() and quantity_in_stock>0;


-- 21) Average shelf life per brand
select brand, avg(shelf_life) as avg_shelf_life
from dairy_info
group by brand
order by avg_shelf_life desc;

-- 22 Most popular product in each customer location
select product_name, customer_location, count(quantity_sold) as total_qty
from dairy_info
group by product_name, customer_location
order by customer_location, total_qty desc;



